### ISSUE TITLE
extracted global concerns

### ISSUE THREAD

**Issue by adamaltman** [RomanGotsiy/redoc-prototype#3]
http://bradfults.com/the-best-api-documentation/#extractedglobalconcerns

**Comment by RomanGotsiy** [comment]
Would you like to see it already in prototype?

**Comment by adamaltman** [comment]
Good question... I think so... but does the petstore spec have anything like this?

**Comment by RomanGotsiy** [comment]
OK. I've already finished all the features planned for prototype so now I can switch to this feature.

Petstore spec doesn't have anything like that but we can extend it to demonstrate. Together with Ivan we came up to the simple solution. It requires only one vendor-extension field or one additional parameter.
This is like part of Ivan's letter:
> We just need to mark tags that represent high level concept or resource and assign methods to it.
Based on them we can create menu structure without duplicating methods.
And for secondary tags create matching sections in menu which will be referenced from tagged methods.
One of the methods is to mark it inside Swagger with vendor extensions and it will be easy solution for handwritten specs.
We could also support runtime options to ReDoc widget which just specify array of secondary tags.
In worst case scenario, when nothing is specified we just implement the same behaviour as SwaggerUI.

**Comment by adamaltman** [comment]
That sounds good to me.  It seems we would still need to organize those high level concepts in a specific sequence, which could be done in the specification array of secondary tags...

**Comment by RomanGotsiy** [comment]
> It seems we would still need to organize those high level concepts in a specific sequence, which could be done in the specification array of secondary tags...

Yes, exactly! :+1:

**Comment by RomanGotsiy** [comment]
The feature is implemented
Currently it supports only marking secondary tags inside Swagger with the vendor extension `x-secondaryTag: true`. Runtime option will be added later.
I've quickly extended Petstore schema so this feature can be explored on the live demo.

How do you feel about general concept of this?
